# https://docs.github.com/en/actions
# https://github.com/marketplace?type=actions
# https://github.com/orgs/actions/repositories?q=&type=all&language=&sort=name

name: main

on: [push, workflow_dispatch]

env:
  MSVC_ROOT: C:\Program Files\Microsoft Visual Studio\2022\Enterprise
  NINJA_CMD: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja\ninja.exe

defaults:
  run:
    shell: cmd

jobs:
  buildAndTest:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3.0.1
      #- uses: actions/cache@3
      #  with:
      #    key: 221111a
      #    path: |
      #      ~/AppData/Local/vcpkg
      #      ./build/cache
      #- name: Scan
      #  run: ./task.ps1 scan
      #  shell: pwsh
      - name: Build
        run: $NINJA_CMD all
      - uses: actions/upload-artifact@v3.1.1
        with:
          path: ./out
          retention-days: 3
