# https://docs.github.com/en/actions
# https://github.com/marketplace?type=actions
# https://github.com/orgs/actions/repositories?q=&type=all&language=&sort=name

name: main

on: [push, workflow_dispatch]

env:
  MSVC_ROOT: C:\Program Files\Microsoft Visual Studio\2022\Enterprise
  CLANG_ROOT: C:\tools\msys64\mingw64\bin

defaults:
  run:
    shell: pwsh

jobs:
  buildAndTest:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          key: 221111a
          path: ~/AppData/Local/vcpkg
      - name: Scan for compilers
        run: ./Task scan
      #- name: Build
      #  run: ./Task build
      #  continue-on-error: true
      - uses: actions/upload-artifact@v3
        with:
          path: ./out/artifact
          retention-days: 2
